### ISSUE TITLE
TRFMask error

### ISSUE THREAD

**Issue by SamCT** [qjiangzhao/TEtrimmer#35]
Hello,

I am attempting to run TEtrimmer on the test files and received the following error:

```
RepeatClassifier failed for rnd_1_family_587 with error code 2
b'Something went wrong with the TRFMask program.  The tmpConsensi.fa.masked file was missing or empty!\n'
This only affects classification but not the consensus sequence. You can run 'RepeatClassifier -consensi <your_consensus_file>' manually.
RepeatClassifier failed for rnd_1_family_667 with error code 2
```

```
All sequences have been analysed!
In the analysed sequences 1 are skipped. Note: not all skipped sequences can have TE Aid plot in the 'TEtrimmer_for_proof_curation' folder.
In the analysed sequences 0 are identified as low copy TE.

TEtrimmer is doing the final classification. It uses the classified TE to classify Unknown elements.
0 TE elements were re-classified by the final classification module.

TEtrimmer is removing sequence duplications. This might take long time when many sequencesare included into the final consensus library. Please be patient!

Finished to remove sequence duplications.

TEtrimmer is clustering TE consensus library. This can potentially take long time when many sequences exist in the consensus library. Please be patient!

Progress: |██████████████████████████████████████████████████| 8/8 = 100.0% Complete


TEtrimmer analysis finished at 2024-07-03 20:38:57.

TEtrimmer runtime was 0:03:49.
```

It looks like my summary.txt file is correct however. How likely is this to impact my actual dataset?

Thanks,
Sam

**Comment by qjiangzhao** [comment]
Hi Sam,

TEtrimmer employed RepeatClassifier (the classification module from RepeatModeler) for TE classification. Your error occurred due to improper configuration of RepeatModeler.

You can try to fix this by running `mamba update -c bioconda repeatmodeler` and testing RepeatClassifier in your terminal manually with: `RepeatClassifier -consensi <your_consensus_file>`.

This error only affects TE classification and doesn't affect the TE consensus sequence at all. You can ignore this error and perform TE classification yourself for the final consensus library.

Yours sincerely,

Jiangzhao

**Comment by ASUQ** [comment]
Hi Jiangzhao,

While running the TEtrimmer with the test data, I also faced the same issue.
I installed the tetrimmer with `mamba create -n tetrimmer -c conda-forge -c bioconda tetrimmer`.
This installed the version 1 of repeatmodeler.

After recreating the conda envirionment with `mamba create -n tetrimmer -c conda-forge -c bioconda tetrimmer 'repeatmodeler=2.0.6', the error didn't occur.

So, it might be worth explicitly requesting the version 2 of repeatmodeler in your conda recipe.
