### ISSUE TITLE
Some usage details about TEtrimmerGUI

### ISSUE THREAD

**Issue by abcyulongwang** [qjiangzhao/TEtrimmer#42]
Dear Jiangzhao

Thank you for the TEtrimmerGUI software developed by your team, which makes it possible for us to generate high-quality and gold-standard TE sets. I still have some questions during use.
After I generated TEtrimmer_consensus_merged.fasta, I counted the number of sequences and found that it was consistent with the number of clusters in the visualization interface. But for example, cluster6 contains both SINE and LINE, and their lengths are very different. How did you generate the consensus sequence in that cluster?

![image](https://github.com/user-attachments/assets/30f26904-310e-4f0b-9db5-4829b0a8e137)

After I manually edit all TEs in cluster6, the high-quality sequences will eventually be saved in "TEtrimmer_saved". Then should I merge these saved results as the final TE sequence for genome annotation? But in this case, wouldn't all the sequences in a cluster6 be introduced into the final annotation result? This will increase redundancy. Do I need to use the cdhitest 80-80-80 parameter to remove redundancy later?
Or should I only manually manage and retain the highest quality TE in cluster6, and discard the others? How should we decide whether to keep or discard this?

This is a question I have during use, I hope to get your answer.

Sincerely
Yulong

**Comment by abcyulongwang** [comment]
Dear Jiangzhao
Thank you for your answer, which solved my doubts.
I think I have understood the meaning. If there are "perfect" or "good" TEs in a cluster, if I don't think they need to be manually managed, I can just choose the longest "perfect" or "good" TE and save it. I can abandon all other members in this cluster.
If a cluster is full of Reco_check or Need_check, I will choose the longest one to edit manually and then save their cons sequence.
Another question is, do you think the quality of genome assembly has a big impact on the results of TEtrimmer? I have many genomes, some of which are of good quality, high-quality genomes at the chromosome level. But many are pseudo-chromosome level genomes, which are obtained by mounting Ragtag on the reference genome, and there are many gap regions in the middle of the genome. You have a lot of experience, and I would like to ask you to judge whether this will have a fatal impact on the accuracy of TE library results based on your experience.
Thank you，Wish you happy every day.

Sincerely
Yulong

**Comment by qjiangzhao** [comment]
Dear Yulong,

Yes, you are right. But before you save the representative TE from one cluster, it is better to check its report PDF file, even it is classified as "Perfect" or "Good". If only "Reco_check"  and "Need_check" exist in a cluster, you can try to inspect the longest one, but the longest one is not always the best one. 
Besides, I want to highlight that the current result evaluation system can't properly assess LINE, SINE, and Helitron because they don't have terminal repeats. For this, I will improve it in the future. 

As for your new question, genome quality can highly affect the performance of TEtrimmer. Because TEtrimmer analysis based on the repetitive nature of TEs, it need to retrieve TE copies from genome. I am working on improving the compatibility to pangenome analysis of TEtrimmer. 

Your sincerely
Jiangzhao

**Comment by abcyulongwang** [comment]
Thank you for your efficient and quick response. I will continue to follow up on the software updates.
Sincerely
Yulong
