### ISSUE TITLE
Some issues with the "cons" step

### ISSUE THREAD

**Issue by abcyulongwang** [qjiangzhao/TEtrimmer#46]
Dear Jiangzhao

I encountered this problem during manual management.

This is a TEAID of a modified multiple alignment of a LINE transposon. It looks OK. But when I run the cons step of TEtrimmer, it becomes like this, without even a complete sequence.

![image](https://github.com/user-attachments/assets/f5d261fc-9082-409b-890a-b138098e0c59)

![image](https://github.com/user-attachments/assets/7e59c42b-8f5b-4472-93eb-fc3cde5ec592)

There are many similar examples. Some transposon cons sequences cannot even run TEAID successfully, and it displays "BLAST hit number is 0 for this sequence."
I guess this means that we can completely abandon these TE sequences because they are of low quality.
I also have an idea. After running TEtrimmer, I want to compare the quality of the TE library with and without manual editing. Do you have any recommended methods for quality comparison? Manual management is too time-consuming and it will be a nightmare for me.

Thank you for your previous reply, wish you happiness every day

Yulong

**Comment by qjiangzhao** [comment]
Hi Yulong,

Thanks for your question. But I am a little bit confused. What is the difference between those provided TE-Aid plots?

Could you explain your question again?

Yours sincerely
Jiangzhao

**Comment by qjiangzhao** [comment]
Dear Yulong,

The "TEAid" button in TEtrimmerGUI can be applied on multiple sequence alignment (MSA) or TE consensus sequence.

If it were a MSA, a consensus sequence will be generated with a threshold of 0.5. This corresponding with your plot:

![image](https://github.com/user-attachments/assets/cd2b37e4-a2ae-4202-8f10-244e1656986a)

When you clikc the "Cons" button, a consensus sequence will be generated with the default  threshold of 0.8. You can also apply "TEAid" button based on this consensus sequence, the corresponding plot is:

![image](https://github.com/user-attachments/assets/0e482318-8cf4-4995-b8bc-213866f6f0d0)

Because the threshold used for consensus sequence generation is different, the "TEAid" plot also exhibited differently especially for poorly conserved TEs (like your LINE element).

You can modify the "Cons" threshold by:

<img width="677" alt="Screenshot 2024-10-16 at 10 17 01" src="https://github.com/user-attachments/assets/8fa52d77-fb16-4311-bbcb-4b846e6527d9">

Based on your Aliveiw shreenshot, I won't discard this LINE element. You can choose to lower the "Cons" threshold number and save your MSA as a HMM model. 

Yours sincerely
Jiangzhao
